name: build

on:
  push:
    branches:
      - main
    paths:
      - 'python-app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'python-app/**'

jobs:
  build:
    name: Build and Scan
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./python-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner and save report
        run: |
          trivy image --format json --output trivy-report.json ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ github.sha }}

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json